### ISSUE TITLE
Error at the end of an upload and YouTube cannot process the video

### ISSUE THREAD

**Issue by vassilevsky** [porjo/youtubeuploader#5]
Hello 👻

I installed the program from archive to Ubuntu 16.04.1 x64 on DigitalOcean.
I used `python3 setup.py install` to install it.
I ran it twice with the same file and both times got the same error:

```
root@ubuntu-512mb-fra1-01:~# youtube-upload -t JC3-2 /var/lib/flussonic/archive/20170126.mp4
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: /var/lib/flussonic/archive/20170126.mp4
100% |#####################################################################################################|   1.42 MB/s
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/main.py", line 177, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/main.py", line 139, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/upload_video.py", line 42, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/lib.py", line 70, in retriable_exceptions
    return fun()
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/upload_video.py", line 40, in <lambda>
    upload_fun = lambda: _upload_to_request(request, progress_callback)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/upload_video.py", line 24, in _upload_to_request
    status, response = request.next_chunk()
  File "/usr/lib/python3/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/googleapiclient/http.py", line 880, in next_chunk
    return self._process_response(resp, content)
  File "/usr/lib/python3/dist-packages/googleapiclient/http.py", line 907, in _process_response
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 502 when requesting https://www.googleapis.com/upload/youtube/v3/videos?part=snippet%2Cstatus%2CrecordingDetails&uploadType=resumable&alt=json returned "Bad Gateway">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/youtube_upload/main.py", line 247, in main
    response = bytes.decode(error.content, encoding=lib.get_encoding()).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1441: ordinal not in range(128)
```

Both videos appeared on YouTube as unprocessed. It has now been ~6 hours since the last one and they still haven't been processed. It looks like they are corrupted.

It would be nice to understand what was the problem.

Thank you!

**Comment by porjo** [comment]
You have the wrong project. I think you're looking for https://github.com/tokland/youtube-upload
